### ISSUE TITLE
how can I run this project?

### ISSUE THREAD

**Issue by sunjiakun** [NextCenturyCorporation/dig#2]
when I run 'grunt build', there are many modules need to install.

**Comment by flyntde** [comment]
@sunjiakun 
> when I run 'grunt build', there are many modules need to install.

Prerequisites
* Node.js
* grunt-cli installed globally (npm i -g grunt-cli)
* Bower installed globally (npm i -g bower)
* [MySQL]
* Elasticsearch

When cloning this repository for the first time, run these two commands:

cd dig

npm install

bower install

The workflow is:

grunt serve # starts the server and opens up the home page in your browser

grunt test # run all of the tests

grunt ... # see Gruntfile.js and documentation for grunt

Once the server is started with grunt, when you modify the application, the browser will refresh and show those changes.
